# mongo-secret.yml
# Secret untuk menyimpan data sensitif seperti username dan password MongoDB.
# Data di-encode dalam base64.
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # Username untuk root user MongoDB (plain text: "admin").
  MONGO_ROOT_USERNAME: YWRtaW4=
  # Password untuk root user MongoDB (plain text: "supersecretpassword").
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
